sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: sky_take_out
    username: root
    password: 200104242

  redis:
    host: localhost
    port: 6379
    database: 0

  wechat:
    appid: wx523f8c19082a2971
    secret: 9ebd9c36b5c4e0ecda21509ffb75ef76

